"""示範資料：1 位管理員 + 4 位老師（2 位已發布、1 位草稿、1 位首次登入）。"""
import io
import json
import random
import uuid

import click
from PIL import Image, ImageDraw

from .db import execute, get_db, insert, local_today, query, ts
from .profiles import publish
from .security import hash_password
from .storage import get_storage

PALETTES = [((222, 236, 247), (30, 96, 145)), ((252, 238, 214), (196, 120, 22)),
            ((225, 243, 233), (46, 125, 84)), ((240, 231, 247), (110, 72, 150))]


def _png(draw_fn, size=(800, 600)):
    img = Image.new("RGB", size, (250, 250, 250))
    draw_fn(ImageDraw.Draw(img), size)
    out = io.BytesIO()
    img.save(out, "PNG", optimize=True)
    return out.getvalue()


def avatar_png(idx):
    bg, fg = PALETTES[idx % len(PALETTES)]

    def d(dr, size):
        w, h = size
        dr.rectangle([0, 0, w, h], fill=bg)
        dr.ellipse([w * .33, h * .18, w * .67, h * .52], fill=fg)                 # 頭
        dr.rounded_rectangle([w * .18, h * .58, w * .82, h * 1.1], 120, fill=fg)  # 肩
    return _png(d, (600, 600))


def classroom_png(seed):
    rnd = random.Random(seed)
    bg, fg = PALETTES[seed % len(PALETTES)]

    def d(dr, size):
        w, h = size
        dr.rectangle([0, 0, w, h], fill=bg)
        dr.rectangle([w * .12, h * .1, w * .88, h * .42], fill=(46, 72, 64))        # 黑板
        dr.rectangle([w * .12, h * .42, w * .88, h * .45], fill=(160, 120, 80))
        for i in range(3):
            x = w * .2 + i * w * .07
            dr.line([x, h * .2, x + w * .05, h * .3], fill=(240, 240, 240), width=4)
        for row in range(2):
            for col in range(4):
                x = w * .1 + col * w * .21
                y = h * .55 + row * h * .2
                dr.ellipse([x + 30, y - 40, x + 70, y], fill=fg)                       # 學生
                dr.rectangle([x, y, x + w * .17, y + 26], fill=(255, 255, 255))         # 桌子
                c = (rnd.randint(80, 200), rnd.randint(120, 200), rnd.randint(150, 230))
                dr.rectangle([x + 20, y - 6, x + 60, y + 6], fill=c)                    # 平板
    return _png(d)


def demo_pdf(title):
    """產生一份極簡、合法的 PDF（無腳本）。"""
    text = f"BT /F1 24 Tf 72 720 Td ({title}) Tj ET BT /F1 12 Tf 72 690 Td (Demo lesson plan generated by seed script.) Tj ET"
    objs = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length " + str(len(text)).encode() + b" >>\nstream\n" + text.encode() + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = io.BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = []
    for i, body in enumerate(objs, 1):
        offsets.append(out.tell())
        out.write(f"{i} 0 obj\n".encode() + body + b"\nendobj\n")
    xref = out.tell()
    out.write(f"xref\n0 {len(objs) + 1}\n0000000000 65535 f \n".encode())
    for off in offsets:
        out.write(f"{off:010d} 00000 n \n".encode())
    out.write(f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode())
    return out.getvalue()


TEACHERS = [
    {
        "username": "t001", "code": "001", "publish": True, "must_change": 0,
        "profile": dict(county="新北市", school_name="新北市板橋區示範國民小學", teacher_name="林怡君", job_title="五年級導師",
                        phone="0912-345-678", contact_email="yijun.lin@example.edu.tw",
                        slogan="讓每個孩子都成為會提問的學習者",
                        philosophy="我相信學習始於好奇。透過數位工具，讓學生從被動接收轉為主動探究，"
                                   "在小組合作中學會表達、傾聽與反思。\n科技只是工具，真正的目標是培養帶得走的能力。"),
        "educations": [("國立臺北教育大學", "數學暨資訊教育學系", "碩士", "2012–2014"),
                       ("國立臺北教育大學", "數學教育學系", "學士", "2008–2012")],
        "experiences": [("新北市板橋區示範國民小學", "五年級導師", "2016–迄今", "擔任資訊融入教學種子教師，帶領校內數位學習社群。"),
                        ("新北市數學輔導團", "輔導員", "2020–迄今", "辦理數學領域數位教學工作坊。")],
        "specialties": [("數學科差異化教學", "運用學習平台分析學習數據，提供分組任務。"),
                        ("生成式 AI 融入教學", ""), ("平板協作學習", "")],
        "awards": [("教育部教學卓越獎 金質獎（團隊）", "教育部", "2024-10", "")],
        "certifications": [("Google 認證教育工作者 Level 2", "Google for Education", "2023-05", ""),
                           ("新北市數位學習精進方案 認證教師", "新北市政府教育局", "2024-12", "")],
        "courses": [dict(grade="五年級", student_count=26, subject="數學", title="分數的乘法：生活中的比例",
                         unit="第四單元 分數的乘法",
                         objectives="1. 理解分數乘以整數與分數的意義。\n2. 能運用分數乘法解決生活情境問題。\n3. 能以數位白板說明解題策略。",
                         intro="以「班級園遊會」為情境，學生分組規劃攤位食材採購，透過平板操作分數條與即時回饋系統，"
                               "從具體操作走向抽象算式。",
                         four_learning="自學：課前觀看因材網影片並完成診斷。\n共學：小組在共編白板上比較解法。\n"
                                       "互學：組間互評與提問。\n導學：教師依即時數據進行差異化引導。",
                         ai_usage="使用生成式 AI 產生不同難度的情境題；學生用 AI 助教檢核自己的解題說明，"
                                  "再由教師引導辨識 AI 回答的錯誤，培養批判思考。")],
    },
    {
        "username": "t002", "code": "002", "publish": True, "must_change": 0,
        "profile": dict(county="臺中市", school_name="臺中市立示範國民中學", teacher_name="陳建宏", job_title="自然科教師兼資訊組長",
                        phone="0922-111-222", contact_email="chienhung@example.edu.tw",
                        slogan="用科技做實驗，用數據說故事",
                        philosophy="科學是一種看世界的方法。我希望學生能自己設計實驗、收集數據，並用證據說服別人。"),
        "educations": [("國立彰化師範大學", "物理學系", "學士", "2006–2010")],
        "experiences": [("臺中市立示範國民中學", "自然科教師", "2011–迄今", ""),
                        ("臺中市立示範國民中學", "資訊組長", "2019–迄今", "")],
        "specialties": [("感測器探究實驗", "結合手機感測器進行物理量測。"), ("數據視覺化", "")],
        "awards": [("臺中市科展 優等指導", "臺中市政府教育局", "2023-04", "")],
        "certifications": [],
        "courses": [dict(grade="八年級", student_count=30, subject="自然科學", title="聲音的祕密：用手機量測頻率",
                         unit="第三章 波動與聲音",
                         objectives="1. 認識頻率、振幅與聲音特性的關係。\n2. 能使用感測 App 收集並分析數據。",
                         intro="學生以手機分貝與頻譜 App 量測不同樂器的聲音，分組比較並以圖表發表結論。",
                         four_learning="自學：預習影片。共學：分組實驗。互學：成果互評。導學：教師聚焦迷思概念。",
                         ai_usage="以 AI 協助整理實驗數據並產生圖表草稿，學生需檢查並修正 AI 的解讀。")],
    },
    {
        "username": "t003", "code": "003", "publish": False, "must_change": 0,
        "profile": dict(county="臺南市", school_name="臺南市示範國民小學", teacher_name="張雅婷", job_title="英語教師",
                        slogan="Learning English, Connecting the World", philosophy="",
                        phone="", contact_email=""),
        "educations": [], "experiences": [], "specialties": [("英語繪本共讀", "")],
        "awards": [], "certifications": [], "courses": [],
    },
    {
        "username": "t004", "code": "004", "publish": False, "must_change": 1,
        "profile": dict(teacher_name="黃志明"),
        "educations": [], "experiences": [], "specialties": [], "awards": [], "certifications": [], "courses": [],
    },
]


def seed(app):
    db = get_db()
    if query("SELECT 1 FROM users LIMIT 1"):
        raise click.ClickException("資料庫已有使用者，為避免覆蓋，已停止建立示範資料。")
    storage = get_storage(app.config)

    def store(pid, uid, category, data, ext, mime, original):
        name = f"{uuid.uuid4().hex}.{ext}"
        storage.put(name, data, mime)
        return insert("INSERT INTO uploaded_files (profile_id, uploaded_by, category, stored_name, original_name,"
                      " mime_type, size_bytes, created_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
                      (pid, uid, category, name, original, mime, len(data), ts()))

    with db.transaction():
        execute("INSERT INTO users (username, password_hash, role, display_name, email, is_active,"
                " must_change_password, created_at, updated_at) VALUES (%s, %s, 'admin', %s, %s, 1, 0, %s, %s)",
                ("admin", hash_password("Admin1234"), "系統管理員", "admin@example.edu.tw", ts(), ts()))
        for idx, t in enumerate(TEACHERS):
            p = t["profile"]
            uid = insert(
                "INSERT INTO users (username, password_hash, role, display_name, email, is_active,"
                " must_change_password, created_at, updated_at) VALUES (%s, %s, 'teacher', %s, %s, 1, %s, %s, %s)",
                (t["username"], hash_password("Demo1234"), p["teacher_name"], p.get("contact_email") or None,
                 t["must_change"], ts(), ts()))
            cols = list(p.keys())
            pid = insert(
                f"INSERT INTO teacher_profiles (user_id, teacher_code, {', '.join(cols)}, created_at, updated_at)"
                f" VALUES (%s, %s, {', '.join(['%s'] * len(cols))}, %s, %s)",
                [uid, t["code"]] + [p[c] or None for c in cols] + [ts(), ts()])
            if idx < 3:
                aid = store(pid, uid, "avatar", avatar_png(idx), "png", "image/png", "avatar.png")
                execute("UPDATE teacher_profiles SET avatar_file_id = %s WHERE id = %s", (aid, pid))
            if t["courses"]:
                for k in range(3):
                    fid = store(pid, uid, "class_photo", classroom_png(idx * 3 + k), "png", "image/png", f"class{k}.png")
                    execute("INSERT INTO teacher_photos (profile_id, file_id, caption, sort_order, created_at)"
                            " VALUES (%s, %s, %s, %s, %s)", (pid, fid, ["小組協作討論", "平板即時回饋", "成果發表"][k], k, ts()))
            for i, r in enumerate(t["educations"]):
                execute("INSERT INTO educations (profile_id, school, department, degree, period, sort_order, created_at)"
                        " VALUES (%s, %s, %s, %s, %s, %s, %s)", (pid, *r, i, ts()))
            for i, r in enumerate(t["experiences"]):
                execute("INSERT INTO teaching_experiences (profile_id, organization, role, period, description,"
                        " sort_order, created_at) VALUES (%s, %s, %s, %s, %s, %s, %s)", (pid, *r, i, ts()))
            for i, r in enumerate(t["specialties"]):
                execute("INSERT INTO specialties (profile_id, name, description, sort_order, created_at)"
                        " VALUES (%s, %s, %s, %s, %s)", (pid, *r, i, ts()))
            for i, r in enumerate(t["awards"]):
                execute("INSERT INTO awards (profile_id, title, issuer, award_date, description, sort_order, created_at)"
                        " VALUES (%s, %s, %s, %s, %s, %s, %s)", (pid, *r, i, ts()))
            for i, r in enumerate(t["certifications"]):
                execute("INSERT INTO certifications (profile_id, name, issuer, cert_date, description, sort_order,"
                        " created_at) VALUES (%s, %s, %s, %s, %s, %s, %s)", (pid, *r, i, ts()))
            for i, c in enumerate(t["courses"]):
                names = list(c.keys())
                cid = insert(f"INSERT INTO courses ({', '.join(names)}, profile_id, sort_order, created_at, updated_at)"
                             f" VALUES ({', '.join(['%s'] * len(names))}, %s, %s, %s, %s)",
                             [c[n] for n in names] + [pid, i, ts(), ts()])
                for ptype, title in (("lesson_plan", "完整教案"), ("material", "學習單")):
                    fid = store(pid, uid, ptype, demo_pdf(f"{t['code']} {ptype}"), "pdf", "application/pdf",
                                f"{c['title']}_{title}.pdf")
                    execute("INSERT INTO lesson_plans (profile_id, course_id, file_id, title, plan_type, created_at)"
                            " VALUES (%s, %s, %s, %s, %s, %s)", (pid, cid, fid, title, ptype, ts()))

    # 補縮圖，再用正式的發布函式發布，確保與線上行為一致（也會寫入發布歷史）
    from .uploads import backfill_thumbnails
    backfill_thumbnails(db, storage)
    for t in TEACHERS:
        if t["publish"]:
            publish(query("SELECT p.id FROM teacher_profiles p JOIN users u ON u.id = p.user_id WHERE u.username = %s",
                          (t["username"],), one=True)["id"])
    # 示範公告與少量瀏覽數（讓總覽與後台的統計有東西可看）
    from datetime import datetime, timedelta
    today = datetime.strptime(local_today(), "%Y-%m-%d")
    execute("INSERT INTO announcements (title, body, starts_on, ends_on, is_pinned, created_at, updated_at)"
            " VALUES (%s, %s, NULL, NULL, 1, %s, %s)",
            ("歡迎使用教師數位課程展示平台", "請於截止日前完成基本資料、課堂照片與至少一門數位課程，"
             "並記得按下「發布」。如有問題請聯繫承辦人。", ts(), ts()))
    execute("INSERT INTO settings (key, value) VALUES ('deadline', %s)",
            ((today + timedelta(days=21)).strftime("%Y-%m-%d"),))
    rnd = random.Random(7)
    for code in ("001", "002"):
        pid = query("SELECT id FROM teacher_profiles WHERE teacher_code = %s", (code,), one=True)["id"]
        for d in range(30):
            day = (today - timedelta(days=d)).strftime("%Y-%m-%d")
            execute("INSERT INTO page_views (profile_id, day, views) VALUES (%s, %s, %s)",
                    (pid, day, rnd.randint(0, 9 if code == "001" else 4)))
    click.echo("示範資料建立完成：admin / Admin1234，老師 t001–t004 / Demo1234（t004 首次登入需改密碼）")
